import tkinter as tk
from tkinter import *
def buttonClick(number):
    global val
    val=val+str(number)
    data.set(val)
def buttonClear():
    global val
    val=""
    data.set("")
def buttonEquals():
    expression=display.get()
    try:
        result=eval(expression)
        display.delete(0,tk.END)
        display.insert(tk.END,str(result))
    except Exception:
        display.delete(0,tk.END)
        display.insert(tk.END,"Error")
root=Tk()
root.title("calculator")
val=""
data=StringVar()
root.geometry("500x500")
display=Entry(root,textvariable=data,bd=29,justify="right",bg="light pink",font=("Ariel",22))
display.grid(row=0,columnspan=4)
button7=Button(root,text="7",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(7))
button7.grid(row=1,column=0)
button8=Button(root,text="8",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(8))
button8.grid(row=1,column=1)
button9=Button(root,text="9",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(9))
button9.grid(row=1,column=2)
button_add=Button(root,text="+",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('+'))
button_add.grid(row=1,column=3)
button4=Button(root,text="4",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(4))
button4.grid(row=2,column=0)
button5=Button(root,text="5",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(5))
button5.grid(row=2,column=1)
button6=Button(root,text="6",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(6))
button6.grid(row=2,column=2)
button_sub=Button(root,text="-",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('-'))
button_sub.grid(row=2,column=3)
button1=Button(root,text="1",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(1))
button1.grid(row=3,column=0)
button2=Button(root,text="2",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(2))
button2.grid(row=3,column=1)
button3=Button(root,text="3",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(3))
button3.grid(row=3,column=2)
button_multiply=Button(root,text="*",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('*'))
button_multiply.grid(row=3,column=3)
button0=Button(root,text="0",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(0))
button0.grid(row=4,column=0)
buttonClear=Button(root,text="c",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=buttonClear)
buttonClear.grid(row=5,column=2)
button_division=Button(root,text="/",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('/'))
button_division.grid(row=4,column=3)
buttondot=Button(root,text=".",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('.'))
buttondot.grid(row=4,column=1)
buttonEquals=Button(root,text="=",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=buttonEquals)
buttonEquals.grid(row=4,column=2)
button_bracket=Button(root,text="(",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick('('))
button_bracket.grid(row=5,column=0)
button_bracket=Button(root,text=")",font=("Ariel",12,"bold"),bd=12,height=2,width=6,command=lambda:buttonClick(')'))
button_bracket.grid(row=5,column=1)
root.mainloop()
